#!/usr/bin/env sh
SCRIPTPATH="$( cd "$(dirname "$0")" ; pwd -P )"
if [ -f ${SCRIPTPATH}/../.env ]; then
    . ${SCRIPTPATH}/../.env
fi
echo ${SCRIPTPATH}/../.env
mkdir -p ${SCRIPTPATH}/../res/credentials
curl --user ${REMOTE_DATA_LOGIN}:${REMOTE_DATA_PASSWD} https://files.api.suricats-consulting.com/credentials/services/google.json -o ${SCRIPTPATH}/../res/credentials/google.json
curl --user ${REMOTE_DATA_LOGIN}:${REMOTE_DATA_PASSWD} https://files.api.suricats-consulting.com/credentials/services/forecast.json -o ${SCRIPTPATH}/../res/credentials/forecast.json
curl --user ${REMOTE_DATA_LOGIN}:${REMOTE_DATA_PASSWD} https://files.api.suricats-consulting.com/credentials/services/recast.json -o ${SCRIPTPATH}/../res/credentials/recast.json
